apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  annotations: # CHANGE-CAUSEにコメントを残す
    kubernetes.io/change-cause: "Update nginx 1.17.3"
spec:
  replicas: 2
  selector:
    matchLabels:
        app: web
        env: study
  revisionHistoryLimit: 14 # バージョン履歴
  strategy:
    type: RollingUpdate
    rollingUpdate:
        maxSurge: 1 # レプリカ数を超えてよいPod数
        maxUnavailable: 1 # 一度に消失してよいPod数
  template:
    metadata:
        name: nginx
        labels: 
          app: web
          env: study
    spec:
        containers: 
        - name: nginx
          image: nginx:1.17.3-alpine

# < kubectl rollout history deploy/nginx
# deployment.extensions/nginx
# REVISION  CHANGE-CAUSE
# 1         <none>
          