# kubectl create secret generic sample-secret --from-literal=message='Hello World!' --from-file=./keyfile

# < kubectl get secret
# NAME                  TYPE                                  DATA   AGE
# default-token-bpldx   kubernetes.io/service-account-token   3      2d20h
# sample-secret         Opaque                                2      13s

# ~/desktop/Web-application-practice-course-to-build-with-Docker-Kubernetes/48
# < kubectl get secret/sample-secret -o yaml
# apiVersion: v1
# data:
#   keyfile: WU9VUi1TRUNSRVQtS0VZ
#   message: SGVsbG8gV29ybGQh
# kind: Secret
# metadata:
#   creationTimestamp: "2020-08-23T00:10:08Z"
#   name: sample-secret
#   namespace: default
#   resourceVersion: "105701"
#   selfLink: /api/v1/namespaces/default/secrets/sample-secret
#   uid: d7897b4f-88c4-4b0d-a62b-1608581cbac7
# type: Opaque

apiVersion: v1
kind: Secret
metadata:
  name: sample-secret
data:
    message: SGVsbG8gV29ybGQh
    keyfile: WU9VUi1TRUNSRVQtS0VZ

---

apiVersion: v1
kind: Pod
metadata:
  name: sample
spec:
  containers:
  - name: sample
    image: nginx:1.17.2-alpine
    env:
    - name: MESSAGE
      valueFrom:
        secretKeyRef:
            name: sample-secret
            key: message
    volumeMounts:
    - name: secret-storage
      mountPath: /home/nginx
  volumes:
  - name: secret-storage
    secret:
        secretName: sample-secret
        itmes:
        - key: keyfile
          path: keyfile
    

# < echo -n 'Hello World!' | base64
# SGVsbG8gV29ybGQh

# < echo -n 'YOUR-SECRET-KEY' | base64
# WU9VUi1TRUNSRVQtS0VZ

# < kubectl exec -it sample sh
# / # ls /home/nginx
# keyfile  message
# / # env
# KUBERNETES_PORT=tcp://10.96.0.1:443
# KUBERNETES_SERVICE_PORT=443
# HOSTNAME=sample
# SHLVL=1
# HOME=/root
# PKG_RELEASE=1
# TERM=xterm
# KUBERNETES_PORT_443_TCP_ADDR=10.96.0.1
# NGINX_VERSION=1.17.2
# PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
# KUBERNETES_PORT_443_TCP_PORT=443
# NJS_VERSION=0.3.3
# KUBERNETES_PORT_443_TCP_PROTO=tcp
# KUBERNETES_SERVICE_PORT_HTTPS=443
# KUBERNETES_PORT_443_TCP=tcp://10.96.0.1:443
# MESSAGE=Hello World!
# KUBERNETES_SERVICE_HOST=10.96.0.1
# PWD=/
