apiVersion: v1
kind: PersistentVolume
metadata:
    name: volume-01
spec:
    storageClassName: slow
    accessModes:
    - ReadWriteMany
    capacity:
        storage: 1Gi
    persistentVolumeReclaimPolicy: Retain
    hostPath:
        path: /data/storage
        type: Directory

---

apiVersion: v1
kind: Service
metadata: 
    name: sample-svc
spec:
    clusterIP: None
    selector:
        app: web
        env: study
    ports:
    - port: 80
      targetPort: 80

---

apiVersion: apps/v1
kind: StatefulSet
metadata: 
    name: nginx
spec:
    replicas: 1
    selector:
        matchLabels:
            app: web
            env: study
    revisionHistoryLimit: 14
    serviceName: sample-svc
    template:
        metadata: 
            name: nginx
            labels:
                app: web
                env: study
        spec:
          containers:
              - name: nginx
                image: nginx:1.17.2-alpine
                volumeMounts:
                - name: storage
                  mountPath: /home/nginx
    volumeClaimTemplates:
    - metadata:
        name: storage
      spec: 
          storageClassName: slow
          accessModes:
          - ReadWriteMany
          resources:
              requests:
                  storage: 1Gi
      